theme: jekyll-theme-minimal
title: Jacob A. Hasselbalch
author:
  email: jaha.dbp@cbs.dk
  twitter: jhasselbalch
  github: basselhak
description: Postdoctoral Researcher at the Department of Business and Politics, Copenhagen Business School. 
